name: Backend Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./backend
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./backend
  codeql:
    name: CodeQL Static Code Analysis
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
          config: |
            disable-default-queries: true
            queries:
              - uses: security-extended
              - uses: security-and-quality
      - name: Build .NET Code
        run: dotnet build --no-restore
        working-directory: ./backend
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2