name: Middleware Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Test JUnit5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Compile Maven
        run: mvn compile
        working-directory: ./middleware
      - name: Compile Proto
        run: mvn protobuf:compile
        working-directory: ./middleware
      - name: Run Tests
        run: mvn -B test
        working-directory: ./middleware
  codeql:
    name: CodeQL Static Code Analysis
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          config: |
            disable-default-queries: true
            queries:
              - uses: security-extended
              - uses: security-and-quality
      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./middleware
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
