name: Middleware Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./middleware
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/middleware/target/*.jar'
  deploy:
    name: Deploy Artifacts to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Middleware Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job (.JAR)
        uses: actions/download-artifact@v2
        with:
          name: java-app
      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sep3group1-middleware'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C081E1A184F14A3595C00F5D89D40F7D }}
          package: '*.jar'